/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/models/airplane/model.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const HELIX_SPEED = 6;

export function Airplane(props) {
  const helixRef = useRef();
  const { nodes, materials } = useGLTF("/models/airplane/model.glb");

  useFrame((_state, delta) => {
    helixRef.current.rotation.x += delta * HELIX_SPEED;
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.PUSHILIN_Plane_Circle000.geometry}
        material={materials.plane}
      >
        <meshStandardMaterial color="#ff69b4" />
      </mesh>
      <mesh
        ref={helixRef}
        geometry={nodes.PUSHILIN_Plane_Helix.geometry}
        material={materials.plane}
        position={[1.09, 0.23, 0]}
      >
        <meshStandardMaterial color="#ff69b4" />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/airplane/model.glb");
